version: '3'
services:
  db:
    image: mysql:5
    command: [
        '--wait_timeout=7200',
    ]
    environment:
      MYSQL_DATABASE: 'citadels'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
