swagger: '2.0'
info:
  description: API for the game named Citadels.
  termsOfService: No terms of service.
  title: Citadels API
  version: 0.0.1
host: localhost
basePath: '/'
schemes:
  - http
paths:
  '/status':
    get:
      description: ''
      responses:
        200:
          description: Successful operation
          schema:
            properties:
              message:
                type: string
                example: 'API is running.'
      summary: Requests the status of the API
      tags:
        - status
  '/cards':
    get:
      description: ''
      parameters:
        - default: desc
          description: Sort order
          enum:
            - asc
            - desc
          in: query
          name: sort_order
          required: false
          type: string
        - default: 10
          description: Return limited amount of items, -1 to get all items
          in: query
          name: limit
          required: false
          type: integer
          minimum: 0
          maximum: 50
        - default: 0
          description: Return items starting from this index position
          in: query
          name: offset
          required: false
          type: integer
          minimum: 0
      responses:
        200:
          description: Returns a list of cards
      summary: Requests a list of objects
      tags:
        - cards
  '/cards/districts':
    get:
      description: ''
      parameters:
        - default: desc
          description: Sort order
          enum:
            - asc
            - desc
          in: query
          name: sort_order
          required: false
          type: string
        - default: 10
          description: Return limited amount of items, -1 to get all items
          in: query
          name: limit
          required: false
          type: integer
          minimum: 0
          maximum: 50
        - default: 0
          description: Return items starting from this index position
          in: query
          name: offset
          required: false
          type: integer
          minimum: 0
      responses:
        200:
          description: Returns a list of cards
      summary: Requests a list of objects
      tags:
        - cards
  '/cards/characters':
    get:
      description: ''
      parameters:
        - default: desc
          description: Sort order
          enum:
            - asc
            - desc
          in: query
          name: sort_order
          required: false
          type: string
        - default: 10
          description: Return limited amount of items, -1 to get all items
          in: query
          name: limit
          required: false
          type: integer
          minimum: 0
          maximum: 50
        - default: 0
          description: Return items starting from this index position
          in: query
          name: offset
          required: false
          type: integer
          minimum: 0
      responses:
        200:
          description: Returns a list of cards
      summary: Requests a list of objects
      tags:
        - cards